apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: securehub
data:
  DB_URL: "jdbc:postgresql://postgres:5432/securehub"
  CORS_ALLOWED_ORIGINS: "http://localhost:5173"
  JWT_EXPIRATION_MS: "86400000"
